config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
    end

    #get 'customers/unsubscribe'
    #patch 'customers/withdraw'

    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end

    resources :customers, only: [:show, :edit, :update]
    get 'homes/about'
    get "search" => "searches#search"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: "homes#top"

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name,length: { minimum: 2, maximum: 20 },  presence: true


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("name LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_customer, only: [:show, :edit, :update]

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:updateu] = 'You have updated customer successfully.'
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

private

  def customer_params
    params.require(:customer).permit(:profile_image, :name, :is_deleted)
  end

  def ensure_customer
    @customer = Customer.find(params[:id])
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h3><%= @customer.name %>さんの会員情報編集</h3>
          <div>会員ID <%= @customer.id %></div>
          <div class="form-group mr-3">氏名 <%= @customer.name %></div>
          <div class="form-group mr-3">メールアドレス <%= @customer.email %></div>
        <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
          <div class="form-group mr-3">会員ステータス <%= f.radio_button :is_deleted, "false" %><%= f.label :is_deleted, "有効" %><%= f.radio_button :is_deleted, "true" %><%= f.label :is_deleted, "退会" %></div>
          <div class="form-group mr-3"><%= f.submit "変更を保存", class: "btn btn-info" %></div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/customers/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <h2>会員一覧</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>会員ネーム</th>
              <th></th>
              <th>退会ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
            <tr>
              <td><%= image_tag customer.get_profile_image(40,40) %></td>
              <td><%= customer.name %></td>
              <td><%= link_to "詳細", admin_customer_path(customer.id) %></td>
              <td><%= customer.is_deleted ? "退会" :  "有効" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @customers %>
      </div>
    </div>
  </div>
</main>

app/views/admin/customers/show.html.erb
<main>
  <%= flash[:login] %>
  <%= flash[:updateu] %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'layouts/admincinfo', ipost: @post, customer: @customer %>
      <div class="col-md-8 offset-md-1">
        <h2><%= @customer.name%>さんのレビュー一覧</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>タイトル</th>
              <th>レビュー</th>
              <th>評価</th>
              <th>ジャンル</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |cpost| %>
            <tr>
              <td>
                <%= link_to admin_customer_path(cpost.customer.id) do %>
                  <%= image_tag cpost.customer.get_profile_image(40,40) %></p>
                <% end %>
              </td>
              <td>
                <%= link_to admin_post_path(cpost.id) do %>
                  <%= cpost.title %>
                <% end %>
              </td>
              <td>
                <%= cpost.body %>
              </td>
              <td>
                <div id="star-rate-<%= cpost.id %>"></div>
                  <script>
                  $('#star-rate-<%= cpost.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= cpost.rate %>,
                  });
                  </script>
              </td>
              <td>
                <%= cpost.genre.name %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div><%= link_to "戻る", admin_customers_path, class: "btn btn-outline-info" %></div>
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</main>