config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
    end

    #get 'customers/unsubscribe'
    #patch 'customers/withdraw'

    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end

    resources :customers, only: [:show, :edit, :update]
    get 'homes/about'
    get "search" => "searches#search"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: "homes#top"

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @posts = Post.page(params[:page])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <h1>管理者トップ</h1>
      <div class="col-md-8 offset-md-1">
        <h2>レビュー一覧</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>会員</th>
              <th>タイトル</th>
              <th>レビュー</th>
              <th>評価</th>
              <th>ジャンル</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |review| %>
            <tr>
              <td>
                <%= image_tag review.customer.get_profile_image(100,100) %>
                <%= link_to admin_customer_path(review.customer.id) do %>
                　<%= review.customer.name %>
              　<% end %>
              </td>
              <td>
                <%= link_to admin_post_path(review.id) do %>
                  <%= review.title %>
                <% end %>
              </td>
              <td><%= review.body %></td>
              <td>
                <div id="star-rate-<%= review.id %>"></div>
                  <script>
                  $('#star-rate-<%= review.id %>').empty();
                  $('#star-rate-<%= review.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= review.rate %>,
                  });
                  </script>
              </td>
              <td><%= review.genre.name %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</main>