config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
    end

    #get 'customers/unsubscribe'
    #patch 'customers/withdraw'

    resources :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end

    resources :customers, only: [:show, :edit, :update]
    get 'homes/about'
    get "search" => "searches#search"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: "homes#top"

end

app/views/layouts/_admincinfo.html.erb
<div class="col-md-3">
  <h2>会員情報</h2>
  <div class="img"><%= image_tag customer.get_profile_image(100,100) %></div>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>会員ネーム</th>
        <th><%= customer.name %></th>
      </tr>
      <tr>
    	  <th>レビュー投稿数</th>
    	  <th><%= customer.posts.count %></th>
      </tr>
    </tbody>
  </table>
  <div class="col">
    <div>
      <%= link_to(edit_admin_customer_path(customer), class:"btn btn-outline-dark btn-block") do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_customerinfo.html.erb
<div class="col-md-3">
  <h2>会員情報</h2>
  <div class="img"><%= image_tag customer.get_profile_image(100,100) %></div>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>会員ネーム</th>
        <th><%= customer.name %></th>
      </tr>
      <tr>
    	  <th>レビュー投稿数</th>
    	  <th><%= customer.posts.count %></th>
      </tr>
    </tbody>
  </table>
  <div class="col">
    <div>
      <%= link_to(edit_customer_path(customer), class:"btn btn-outline-dark btn-block") do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/"><span>Game Review</span></a>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <%= render 'layouts/search' %>
          <% if admin_signed_in? %>
            <li class = "nav-item mr-3">
              <%= link_to(admin_customers_path, class:"btn btn-sm btn-outline-secondary") do %>
                会員一覧
              <% end %>
            </li>
            <li class = "nav-item mr-3">
              <%= link_to(admin_posts_path, class:"btn btn-sm btn-outline-secondary") do %>
                投稿一覧
              <% end %>
            </li>
            <li class = "nav-item mr-3">
              <%= link_to(admin_genres_path, class:"btn btn-sm btn-outline-secondary") do %>
                ジャンル一覧
                <% end %>
            </li>
            <li class = "nav-item mr-3">
              <%= link_to(destroy_admin_session_path, method: :delete, class:"btn btn-sm btn-outline-secondary") do %>
                ログアウト
              <% end %>
            </li>
          <% elsif customer_signed_in? %>
            <li class="mx-auto"><p class="logincustomer nav-link text-dark">ようこそ<%= current_customer.name %>さん！</p></li>
            <li class = "nav-item mr-3">
              <%= link_to(customer_path(current_customer), class:"btn btn-sm btn-outline-secondary") do %>
                マイページ
              <% end %>
            </li>
            <li class = "nav-item mr-3">
              <%= link_to(new_post_path, class:"btn btn-sm btn-outline-secondary") do %>
                レビュー投稿
              <% end %>
            </li>
            <li class = "nav-item mr-3">
              <%= link_to(posts_path, class:"btn btn-sm btn-outline-secondary") do %>
                投稿一覧
              <% end %>
            </li>
            <li class = "nav-item mr-3">
              <%= link_to(destroy_customer_session_path, method: :delete , class:"btn btn-sm btn-outline-secondary") do %>
                ログアウト
              <% end %>
            </li>
          <% else %>
            <li class = "nav-item mr-3">
              <%= link_to(homes_about_path, class:"btn btn-sm btn-outline-secondary") do %>
                About
              <% end %>
            </li>
            <li class = "nav-item mr-3">
              <%= link_to(new_customer_registration_path, class:"btn btn-sm btn-outline-secondary") do %>
                新規登録
              <% end %>
            </li>
            <li class = "nav-item mr-3">
              <%= link_to(customer_session_path, class:"btn btn-sm btn-outline-secondary") do %>
                ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if customer_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['Customer'], ['Post']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
     <%= render "layouts/header" %>
    </header>
      <%= yield %>
  </body>
</html>